### PR TITLE
bump to 21.11.10

### PR DESCRIPTION
**Pull request by andyhubbert941**

### CODE REVIEW

**Comment by Erick555** [comment]
@andyhubbert941 @pbek there is https://github.com/flathub/flatpak-external-data-checker which can automate all updates.

**Comment by pbek** [comment]
Thank you for mentioning it, but I'm not sure how to integrate that into the CI release process on GitHub...

**Comment by Erick555** [comment]
@pbek you need to add x-checker-data field under the source, see [examples](https://github.com/flathub/flatpak-external-data-checker#url-templates)

**Comment by pbek** [comment]
I didn't create the flathub repository, so I don't even know how flathub works yet. 😁

**Comment by andyhubbert941** [comment]
> @pbek you need to add x-checker-data field under the source, see [examples](https://github.com/flathub/flatpak-external-data-checker#url-templates)
> 
> You can install this tool from flathub end test manifest.

Hi

I normally push the updates but that too looks good. I am equally not great with flatpak and do it manually updating the files with the correct link, hash and release.

If you are good with flatpak and wish to integrate it then this would be great!! Even if you can give me what I need to do to the files then I can do it to save you needing to fork the repo?

I;ve had a look at the examples but I;/n unsure how to do this!

Thanks

**Comment by pbek** [comment]
Something would need to detect the latest release and its version number and the checksum of the file.

**Comment by andyhubbert941** [comment]
> Something would need to detect the latest release and its version number and the checksum of the file.

I agree - I'm not sure how it works when we have 'static' files sitting on here. E.g. what triggers it to check for an update? I have opened a new issue so hopefully @Erick555 can give us some input

**Pull request merged**
