### PR TITLE
Migrate to GitHub releases

### PR DESCRIPTION
**Pull request by pbek**
For https://github.com/pbek/QOwnNotes/issues/2799

### CODE REVIEW

**Comment by pbek** [comment]
@Erick555, @stobbsm

**Comment by pbek** [comment]
That will not test the updater, of course. 🙄 
I'll merge it to test it.

**Comment by Erick555** [comment]
You can test manifest locally with this [flatpak](https://github.com/flathub/org.flathub.flatpak-external-data-checker)

**Comment by pbek** [comment]
Not if you are on NixOS 🤣

**Pull request merged**
