### PR TITLE
Update to 24.7.0 and unbreak CI

### PR DESCRIPTION
**Pull request by Erick555**

### CODE REVIEW

**Comment by Erick555** [comment]
@pbek please merge. From now you need to merge PRs manually

**Comment by pbek** [comment]
> From now you need to merge PRs manually

@Erick555, what happened to automatic merging?

**Comment by pbek** [comment]
I think the main problem is, I didn't publish the app, so I can't do anything...

**Comment by Erick555** [comment]
but you have the Collaborator status in github repo. Can you login at https://docs.flathub.org/docs/for-app-authors/verification/#im-publishing-an-app-on-flathub-how-do-i-get-it-verified ?

**Comment by pbek** [comment]
No, I don't see the app in the developer tab.

**Comment by Erick555** [comment]
@bbhtt any idea?

**Comment by bbhtt** [comment]
> If the app was [verified](https://docs.flathub.org/docs/for-app-authors/verification) then it can get an allowance

Just verifying it won't be enough, there needs to be an acceptable reason supplied too.

> No, I don't see the app in the developer tab.

Hit the refresh button a few times and wait for a while https://docs.flathub.org/docs/for-app-authors/submission#i-cant-see-the-app-in-my-authored-apps-on-the-developer-portal-why

image

**Comment by Erick555** [comment]
> Just verifying it won't be enough, there needs to be an acceptable reason supplied too.

I meant if it was verified before enacting the ban for auto updates then it would be grandfathered__ with exemption.

**Comment by pbek** [comment]
I've integrated the verification in https://github.com/pbek/QOwnNotes/commit/9ceccc9c54761d584f7c3c07108e182071dc1847. The app should now be verified.

**Comment by pbek** [comment]
And it is: https://flathub.org/apps/org.qownnotes.QOwnNotes

image

But what are those failing checks?

**Comment by Erick555** [comment]
I don't know - I don't have such warning shown.

**Comment by bbhtt** [comment]
You are failing some quality guidelines

These 3 specifically

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#brand-colors

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#not-too-long-1

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#just-the-app-window


image


Fixing them, will make the app eligible to be featured on the flathub.org front page banner/App of the day. If you fix them, click "request review"

**Comment by pbek** [comment]
Thank you, I did things, and I am waiting on the new review...

**Comment by pbek** [comment]
And one more turn...

**Comment by pbek** [comment]
> Flathub [banned](https://discourse.flathub.org/t/linter-breaking-change-restricting-automatic-merge/6922) it due to potential misuse (merging untested and broken changes). If the app was [verified](https://docs.flathub.org/docs/for-app-authors/verification) then it can get an allowance but it's too late although you still can verify it.

@Erick555, could we now attempt to turn on auto-merging again?

**Comment by Erick555** [comment]
see the https://github.com/flathub/org.qownnotes.QOwnNotes/pull/271#issuecomment-2206082899

> Just verifying it won't be enough, there needs to be an acceptable reason supplied too.

You need to open issue at https://github.com/flathub-infra/flatpak-builder-lint/issues and provide reason why your app should be exempted, i.e. all releases are tested upstream and there are no other dependencies which can break something when updated.

**Comment by pbek** [comment]
Thank you, I tried so in https://github.com/flathub-infra/flatpak-builder-lint/issues/428.

**Pull request merged**
